sudo: required

language: bash
services: docker

before_install:
- docker version
- docker info
- docker pull fedora:26

script:
- docker build -t makenv/encoder .
- docker run --rm fedora:26 /bin/bash ls
- docker run --rm makenv/encoder /bin/bash ls
- docker login --username=${DOCKER_USERNAME} --password=${DOCKER_PASSWORD}
- docker push makenv/encoder
